
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6937

mybatis:
  #指定mapper.xml文件位置。此处是通过classpath资源路径指定，还可通过接口包路径，@MapperScan注解等方式指定
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
#  type-aliases-package: com.example.demo.bean
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
    use-generated-keys: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete
      logic-delete-value: 1
      logic-not-delete-value: 0
